name: Publish Docs
on:   
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  publish-docs:
    permissions:
      id-token: write
      contents: read
    uses: ngmd-repo/ngmd-pipelines/.github/workflows/firebase-deploy.yml@v1
    with:
      build-script: npm run docs:all:build
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
